version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Url@666
      POSTGRES_DB: url_shortener
    ports:
      - '5432:5432'
    volumes:
      - url_shortener_data:/var/lib/postgresql/data
      - ./backup:/backup
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: email
    ports:
      - '8080:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  url_shortener_data:
